# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Freak does Geek (Celebrate the unique)
email: freakdoesgeek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site for musings and occasional releases of the freak does geek podcast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://freakdoesgeek.co.uk" # the base hostname & protocol for your site
twitter_username: freakdoesgeek
github_username:  freakdoesgeek

# Build settings
markdown: kramdown
